/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tunts.challenge;

import com.tunts.challenge.service.StudentController;
import com.tunts.challenge.util.Handler;
import com.tunts.challenge.util.Logger;

public class App {

    public static void main( String[] args ) 
    {
        try 
        {
            Logger.logInfo( "Starting App");
            StudentController.getInstance().doWork();
            Logger.logInfo( "Finishing App" );
        } 
        catch( Exception e ) 
        {
            Handler.handle( e );
        }
        finally
        {
            Logger.dump();
        }
    }
}
