/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tunts.challenge;

import com.tunts.challenge.service.StudentController;
import com.tunts.challenge.util.Handler;

import io.github.cdimascio.dotenv.Dotenv;

public class App {

    public static void main( String[] args ) 
    {
        try 
        {
            StudentController.getInstance().doWork();
        } 
        catch( Exception e ) 
        {
            Handler.handle( e );
        }

    }
}
